/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as CoursesLayoutRouteImport } from './routes/courses/_layout'
import { Route as CoursesCoursesRouteImport } from './routes/courses/courses'
import { Route as CoursesGenerateRouteImport } from './routes/courses/generate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesLayoutRoute = CoursesLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesCoursesRoute = CoursesCoursesRouteImport.update({
  id: '/courses/courses',
  path: '/courses/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesGenerateRoute = CoursesGenerateRouteImport.update({
  id: '/courses/generate',
  path: '/courses/generate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/courses': typeof CoursesLayoutRoute
  '/courses/courses': typeof CoursesCoursesRoute
  '/courses/generate': typeof CoursesGenerateRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/courses': typeof CoursesIndexRoute
  '/courses/courses': typeof CoursesCoursesRoute
  '/courses/generate': typeof CoursesGenerateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/courses/_layout': typeof CoursesLayoutRoute
  '/courses/courses': typeof CoursesCoursesRoute
  '/courses/generate': typeof CoursesGenerateRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/courses'
    | '/courses/courses'
    | '/courses/generate'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/courses'
    | '/courses/courses'
    | '/courses/generate'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/courses/_layout'
    | '/courses/courses'
    | '/courses/generate'
    | '/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  CoursesCoursesRoute: typeof CoursesCoursesRoute
  CoursesGenerateRoute: typeof CoursesGenerateRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/_layout': {
      id: '/courses/_layout'
      path: ''
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesLayoutRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/courses': {
      id: '/courses/courses'
      path: '/courses/courses'
      fullPath: '/courses/courses'
      preLoaderRoute: typeof CoursesCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/generate': {
      id: '/courses/generate'
      path: '/courses/generate'
      fullPath: '/courses/generate'
      preLoaderRoute: typeof CoursesGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  CoursesCoursesRoute: CoursesCoursesRoute,
  CoursesGenerateRoute: CoursesGenerateRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
